name: Build
on:
  push: # push 时触发, 主要是为了测试配置有没有问题
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r26b
      - shell: bash
        run: mkdir toolchains
      - name: specify NDK
        uses: ravinderjangra/android-ndk-toolchain-setup@0.2
        with:
          api: '19'
          arch: 'x86'
          install-location: 'toolchains'
          force: true
      - name: Verify zipalign and apksigner installation
        run: |
          zipalign -help
          apksigner --help
  
