name: Build
on:
  push: # push 时触发, 主要是为了测试配置有没有问题
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:

            
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Android SDK Tools
        uses: android-actions/setup-android@v3.2.1
      - name: Verify zipalign and apksigner installation
        run: |
          zipalign -help
          apksigner --help
      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1.5.0
        with:
          ndk-version: r26b

  
