name: Build
on:
  push: # push 时触发, 主要是为了测试配置有没有问题
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1.5.0
        with:
          ndk-version: r26b
      - name: Verify zipalign and apksigner installation
        run: |
          zipalign -help
          apksigner --help
  
