name: Build
on:
  push: # push 时触发, 主要是为了测试配置有没有问题
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:

            
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Android SDK Tools
        uses: android-actions/setup-android@v3.2.1
        with:
          packages: 'platform-tools platforms;android-34 build-tools;34.0.0'

      - name: Output build-tools path and add to PATH
        run: |
          echo "Build-tools path: ${ANDROID_SDK_ROOT}/build-tools/34.0.0"
          ls -la ${ANDROID_SDK_ROOT}/build-tools/34.0.0
          echo "${ANDROID_SDK_ROOT}/build-tools/34.0.0" >> $GITHUB_PATH

      - name: Verify zipalign and apksigner installation
        run: |
          zipalign -help
          apksigner --help
      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1.5.0
        with:
          ndk-version: r26b

  
