name: Sync Fork

on:
  push: # push 时触发, 主要是为了测试配置有没有问题
  schedule:
    - cron: '* */3 * * *' # 每3小时触发, 对于一些更新不那么频繁的项目可以设置为每天一次, 低碳一点
permissions:
  actions: write
  contents: write
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - uses: tgymnich/fork-sync@v1.8
        with:
          token: ${{ secrets.TOKEN }}
          owner: AzurLaneTools
          repo: AzurLaneLuaScripts
          head: main
          base: main
          retries: 1
          retry_after: 10
          ignore_fail: true
