name: Sync Fork

on:
  schedule:
    - cron: '20 0 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: main
    - name: Fetch upstream
      run: |
        ls
        git remote add upstream https://github.com/AzurLaneTools/AzurLaneLuaScripts.git
        git fetch upstream
        git log --all
        git merge-base main upstream/main
        git merge upstream/main
        git push
