name: Sync Fork

on:
  schedule:
    - cron: '20 0 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: main
    - name: Fetch upstream
      run: |
        git remote add upstream https://github.com/AzurLaneTools/AzurLaneLuaScripts.git
        git fetch upstream
    - name: Merge upstream
      run: |
        git merge upstream/main
    - name: Push to fork
      run: |
        git push
