
name: UpdateApk

on:
  push: # push 时触发, 主要是为了测试配置有没有问题
  workflow_dispatch:
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - uses: szenius/set-timezone@v1.2
        with:
          timezoneLinux: "Asia/Singapore"
          timezoneMacos: "Asia/Singapore"
          timezoneWindows: "Singapore Standard Time"
      - uses: actions/checkout@v3
      - name: Checkout AzurLaneApk
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.TOOLS_REPOSITORY }}
          token: ${{ secrets.TOKEN }}
          path: AzurLaneApk
          ref: JP
#       - name: Install Clang
#         uses: egor-tensin/setup-clang@v1.4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake clang

      - name: Create build directory
        run: mkdir build

      - name: Configure CMake
        working-directory: build
        run: |
          cmake .. -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++

      - name: Build project
        working-directory: build
        run: make
      - name: Run scripts
        run: |
            ./gametip
            ./ship_data_statistics
        working-directory: Output/bin
      - name: move output file
        run: |
            cp gametip.h ../AzurLaneApk/jni/Includes/adjust/gametips.h
            cp ship_data_statistics.h ../AzurLaneApk/jni/Includes/adjust/ship_data_statistics.h
        working-directory: Output

      - name: Commit files
        run: |
          git config  user.email "github-actions[bot]@users.noreply.github.com"
          git config  user.name "github-actions[bot]"
          if [[ `git status --porcelain` ]]; then
            git commit -a -m "Changes *.h"
            echo "::set-output name=has_changes::true"
          else
            echo "No changes to commit"
            echo "::set-output name=has_changes::false"
          fi
        working-directory: AzurLaneApk

      - name: Setup Android NDK >=23
        if: steps.check_changes.outputs.has_changes == 'true'
        # You may pin to the exact commit or the version.
        # uses: anoop-b/setup-ndk@6f0ee78e62451cfec5f1698acb00b58d00a5d7b6
        uses: anoop-b/setup-ndk@V1.3.0
        with:
          # Exact version to use
          ndk-version: r25b
          # Add installation directory to the PATH
          add-to-path: true
          # Use the local job cache on top of the runner tool cache
          local-cache: true
      - name: build
        if: steps.check_changes.outputs.has_changes == 'true'
        run: |
          ndk-build NDK_APPLICATION_MK=Application.mk APP_BUILD_SCRIPT=Android.mk NDK_OUT=..\
        working-directory: AzurLaneApk/jni

      - name: Commit files
        if: steps.check_changes.outputs.has_changes == 'true'
        run: |
          git config  user.email "github-actions[bot]@users.noreply.github.com"
          git config  user.name "github-actions[bot]"
          if [[ `git status --porcelain` ]]; then
            git commit -a -m "Changes libs"
            git push
          else
            echo "No changes to commit"
          fi
        working-directory: AzurLaneApk


      - name: Checkout azurlane-JP
        uses: actions/checkout@v3
        with:
          repository: liusj5257/azurlane-JP
          token: ${{ secrets.TOKEN }}
          path: azurlane-JP
      - name: Setup Java JDK
        uses: actions/setup-java@v3.3.0
        with:
          java-version: "17"
          distribution: "adopt"

      - name: move libs file
        run: |
            cp -r libs/. ../azurlane-JP/libs
        working-directory: AzurLaneApk

      - name: Commit libs
        run: |
          git config  user.email "github-actions[bot]@users.noreply.github.com"
          git config  user.name "github-actions[bot]"
          if [[ `git status --porcelain` ]]; then
            git commit -a -m "Changes libs"
            git push
            echo "::set-output name=libs_changes::true"
          else
            echo "No changes to commit"
            echo "::set-output name=libs_changes::false"
          fi
        working-directory: azurlane-JP


      - name: Build Perseus APK
        if: steps.check_changes.outputs.libs_changes == 'true'
        run: ./patch_perseus.sh
        working-directory: azurlane-JP

      - name: Zipalign and Sign Android release
        if: steps.check_changes.outputs.libs_changes == 'true'
        run: ./zipalign_sign.sh
        working-directory: azurlane-JP

      - name: Create Release
        if: steps.check_changes.outputs.libs_changes == 'true'
        uses: ncipollo/release-action@v1.12.0
        with:
          allowUpdates: true
          artifactErrorsFailBuild: true
          artifacts: azurlane-JP/build/*.apk
          draft: true
#           commit: "latest"
          makeLatest: true
          tag: "latest"
          omitBody: true

