
name: UpdateApk

on:
#   push: # push 时触发, 主要是为了测试配置有没有问题
  workflow_dispatch:
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - uses: szenius/set-timezone@v1.2
        with:
          timezoneLinux: "Asia/Singapore"
          timezoneMacos: "Asia/Singapore"
          timezoneWindows: "Singapore Standard Time"    
      - uses: actions/checkout@v3
      - name: Checkout apk repo
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.TOOLS_REPOSITORY }}
          token: ${{ secrets.TOOLS_DEPLOY_KEY }}
          path: AzurLaneApk
          ref: JP
      - name: Run scripts
        run: |
            gametips.exe
            ship_data_statistics.exe
        working-directory: Output/bin
